[theme]
primaryColor = "#3182f6"
backgroundColor = "#f4f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#191f28"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
